const COLORS = {
  PRIMARY: '#EEEEFA',
  SECONDARY: '#13378D',
  PRIMARY_TEXT: '#323232',
  SECONDARY_TEXT: '#FFFFFF',
  PLACEHOLDER: '#9E9E9E',
  WARNING: '#B00020',
  INPUT_BACKGROUND: '#FCFCFD',
  INPUT_BORDER: '#CCCCCC',
};

export default COLORS;
